# Generated by Django 4.0.2 on 2022-02-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_playlist_imdids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imdids',
            name='user',
        ),
    ]
