# Generated by Django 4.0.2 on 2022-02-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_playlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
